name: Notify

on:
  workflow_run:
    workflows: ["Arma"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Rezent
        env:
          REZENT_TOKEN: ${{ secrets.REZENT_TOKEN }}
          REZENT_URI: ${{ secrets.REZENT_URI }}
        run: |
          curl -H "Authorization: Bearer ${REZENT_TOKEN}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -X POST \
            -d '{"organisation": "Piq-Pen", "repository": "ZEN", "workflow_id": 650750}' \
            "$REZENT_URI"
